language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r microbenchmark knitr arules testthat timeDate"
- "./travis-tool.sh github_package jimhester/covr"
- "./travis-tool.sh install_github robertzk/statsUtils robertzk/stagerunner robertzk/mungebits
  robertzk/Ramd robertzk/testthatsomemore"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: Q5oby92K0if7YFkV8omcbD/gGaWf0GTms4K7EuEM7UsHMcBTY+84W+qc66/WCpfgE92hdatK9k37VxeOnl4CTCYHkRAlB7PKK/TjKkhywuAwDMfKFa2fb/uCujXuLEslx0D93yZ1Jpb5K+nfH3ga9kzB4e3TPRKGrvnZ5hHUy4M=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
